spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 556677
    url: jdbc:mysql://39.106.161.181:3306/springcache?useUnicode=true&characterEncoding=utf-8&useSSL=false
mybatis:
  type-aliases-package: cn.spring.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #  驼峰命名
logging:
  level:
    cn.cache.dao: debug  # 开启日志功能,查看缓存使用情况
